pipeline:
  identifier: Build_dkhopade_tanzu_java_web_app_1709839445942
  name: Build tanzu-java-web-app
  orgIdentifier: default
  projectIdentifier: test
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: dkhopade/tanzu-java-web-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
